name: "Build and publish"

on:
  push:
    tags:
      - "v*.*.*"

env:
  IGNORED_FILES: '[ "Makefile", "README.md", "manifest_*.json", "build.sh" ]'

jobs:
  build-and-sign:
    name: "Build and sign"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mv manifest_firefox.json manifest.json
      - name: "Build Firefox extension"
        id: firefox-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          ignoreFiles: ${{ env.IGNORED_FILES }}
          filename: "{name}-{version}-firefox.xpi"
      - run: mv manifest.json manifest_firefox.json && mv manifest_chromium.json manifest.json
      - name: "Build Chromium extension"
        id: chromium-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          ignoreFiles: ${{ env.IGNORED_FILES }}
          filename: "{name}-{version}-chromium.zip"
      - run: mv manifest.json manifest_chromium.json
      - name: "Sign Firefox extension"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.firefox-build.outputs.target }}
          filename: "{name}-{version}-firefox-signed.xpi"
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000
      - name: "Upload extensions"
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            ${{ steps.chromium-build.outputs.target }}
            ${{ steps.web-ext-sign.outputs.target }}

  release:
    name: "Release"
    needs: build-and-sign
    runs-on: ubuntu-latest
    permissions:
      contents: write # For creating a release
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: build
      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: ${{ steps.download.outputs.download-path }}* # Upload all files from the artifact

  deploy:
    name: "Deploy to GitHub pages"
    needs: release
    runs-on: ubuntu-latest
    permissions:
      pages: write # Needed for deploying to GitHub pages
      id-token: write # To verify the deployment originates from an appropriate source
    steps:
      - run: mkdir out
      - name: "Generate update manifest"
        uses: 2zqa/generate-update-manifest@2a90b178b37fd79513dfd2ec7dae7eace7a45f2a
        with:
          addon-id: ${{ vars.ADDON_ID }}
          output-file: out/updates.json
      - uses: actions/upload-pages-artifact@v2
        with:
          name: update-manifest
          path: out
      - uses: actions/deploy-pages@v2
        id: deploy
        with:
          artifact_name: "update-manifest"
      - run: |
          echo "Deployed update manifest to ${{ steps.deploy.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
